builder:
  track: dev

labels:
  team: estafette-team
  language: helm

version:
  semver:
    major: 1
    minor: 11
    patch: 1

stages:
  download-istio:
    image: alpine:3.14
    commands:
    - apk add curl
    - curl -L https://istio.io/downloadIstio | ISTIO_VERSION=${ESTAFETTE_BUILD_VERSION} TARGET_ARCH=x86_64 sh -
    - mv istio-${ESTAFETTE_BUILD_VERSION}/manifests/charts helm
    - mv helm/gateways/* helm
    - mv helm/istio-control/* helm
    - mv helm/base helm/istio-base

  lint-and-package:
    parallelStages:
      lint-istio-base:
        image: extensions/helm:dev
        action: lint
        chart: istio-base

      lint-istio-cni:
        image: extensions/helm:dev
        action: lint
        chart: istio-cni

      lint-istio-discovery:
        image: extensions/helm:dev
        action: lint
        chart: istio-discovery

      lint-istio-egress:
        image: extensions/helm:dev
        action: lint
        chart: istio-egress

      lint-istio-ingress:
        image: extensions/helm:dev
        action: lint
        chart: istio-ingress

      lint-istio-operator:
        image: extensions/helm:dev
        action: lint
        chart: istio-operator

      lint-istiod-remote:
        image: extensions/helm:dev
        action: lint
        chart: istiod-remote

      package-istio-base:
        image: extensions/helm:dev
        action: package
        chart: istio-base

      package-istio-cni:
        image: extensions/helm:dev
        action: package
        chart: istio-cni

      package-istio-discovery:
        image: extensions/helm:dev
        action: package
        chart: istio-discovery

      package-istio-egress:
        image: extensions/helm:dev
        action: package
        chart: istio-egress

      package-istio-ingress:
        image: extensions/helm:dev
        action: package
        chart: istio-ingress

      package-istio-operator:
        image: extensions/helm:dev
        action: package
        chart: istio-operator

      package-istiod-remote:
        image: extensions/helm:dev
        action: package
        chart: istiod-remote

  clone-charts-repo:
    image: extensions/git-clone:dev
    repo: helm-charts
    branch: main

  list-directory:
    image: alpine:3.14
    commands:
    - ls -latr

  publish-istio-base:
    image: extensions/helm:dev
    action: publish
    chart: istio-base

  publish-istio-cni:
    image: extensions/helm:dev
    action: publish
    chart: istio-cni

  publish-istio-discovery:
    image: extensions/helm:dev
    action: publish
    chart: istio-discovery

  publish-istio-egress:
    image: extensions/helm:dev
    action: publish
    chart: istio-egress

  publish-istio-ingress:
    image: extensions/helm:dev
    action: publish
    chart: istio-ingress

  publish-istio-operator:
    image: extensions/helm:dev
    action: publish
    chart: istio-operator

  publish-istiod-remote:
    image: extensions/helm:dev
    action: publish
    chart: istiod-remote

  create-github-release:
    image: extensions/github-release:dev
    ignoreMissingMilestone: true